# Change these first
owner: Snipey # Your GitHub username
repo: uptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Google
    url: https://www.google.com
  - name: Broken Site
    url: https://thissitedoesnotexist.com
  - name: Secret Site
    url: $SECRET_SITE
  - name: TCP ping
    url: 24.10.60.129:25569

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.snipey.dev
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
